import type { Track } from '@/types/track';
import { CURRENT_USER } from './trackDisplay';

export const GENRES = ['장르 전체', 'Jazz', 'Pop', 'Blues', '기타'] as const;

const JAZZ_STANDARD_PROGRESSION: Track['chordProgression'] = [
  ['CM7', 'AM7', null, null],
  ['AM7', null, 'AM7', null],
  ['CM7', null, 'G7', null],
  ['G7', null, null, null],
  ['CM7', null, 'G7', null],
  ['G7', null, null, null],
  ['CM7', 'AM7', null, null],
  ['AM7', null, 'AM7', null],
];

export const RECOMMENDED_TRACKS: Track[] = [
  {
    id: 'recommended-1',
    title: 'Jazz Standard Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'Cmaj7' },
      { measureNo: 2, sequenceNo: 1, chordName: 'Am7' },
      { measureNo: 3, sequenceNo: 1, chordName: 'Dm7' },
      { measureNo: 4, sequenceNo: 1, chordName: 'G7' },
    ],
    genre: 'Jazz',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:30',
    popularity: 92,
    createdAt: '2026-07-01',
    creator: 'ADMIN',
    chordProgression: JAZZ_STANDARD_PROGRESSION,
  },
  {
    id: 'recommended-2',
    title: 'Pop Ballad Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'G' },
      { measureNo: 2, sequenceNo: 1, chordName: 'Em' },
      { measureNo: 3, sequenceNo: 1, chordName: 'C' },
      { measureNo: 4, sequenceNo: 1, chordName: 'D' },
    ],
    genre: 'Pop',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:50',
    popularity: 88,
    createdAt: '2026-07-02',
    creator: 'ADMIN',
  },
  {
    id: 'recommended-3',
    title: 'Blues in C',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'C7' },
      { measureNo: 2, sequenceNo: 1, chordName: 'F7' },
      { measureNo: 3, sequenceNo: 1, chordName: 'C7' },
      { measureNo: 4, sequenceNo: 1, chordName: 'G7' },
    ],
    genre: 'Blues',
    bpm: 90,
    difficulty: 'intermediate',
    duration: '2:30',
    popularity: 81,
    createdAt: '2026-06-28',
    creator: 'ADMIN',
  },
  {
    id: 'recommended-4',
    title: 'Rock Riff Practice',
    key: 'E',
    mode: 'minor',
    timeSignature: '4/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'Em' },
      { measureNo: 2, sequenceNo: 1, chordName: 'C' },
      { measureNo: 3, sequenceNo: 1, chordName: 'G' },
      { measureNo: 4, sequenceNo: 1, chordName: 'D' },
    ],
    genre: '기타',
    bpm: 140,
    difficulty: 'intermediate',
    duration: '1:20',
    popularity: 76,
    createdAt: '2026-07-03',
    creator: 'ADMIN',
  },
];

export const ALL_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Jazz Standard Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'Cmaj7' },
      { measureNo: 2, sequenceNo: 1, chordName: 'Am7' },
      { measureNo: 3, sequenceNo: 1, chordName: 'Dm7' },
      { measureNo: 4, sequenceNo: 1, chordName: 'G7' },
    ],
    genre: 'Jazz',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:30',
    popularity: 92,
    createdAt: '2026-07-01',
    creator: 'ADMIN',
    chordProgression: JAZZ_STANDARD_PROGRESSION,
  },
  {
    id: 'track-3',
    title: 'Jazz Waltz Practice',
    key: 'G',
    mode: 'major',
    timeSignature: '3/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'Gmaj7' },
      { measureNo: 2, sequenceNo: 1, chordName: 'Em7' },
      { measureNo: 3, sequenceNo: 1, chordName: 'CM7' },
      { measureNo: 4, sequenceNo: 1, chordName: 'D7' },
    ],
    genre: 'Jazz',
    bpm: 100,
    difficulty: 'beginner',
    duration: '1:10',
    popularity: 68,
    createdAt: '2026-07-05',
    creator: CURRENT_USER,
    chordProgression: [
      ['GM7', 'Em7', null],
      ['Em7', null, 'Em7'],
      ['CM7', null, 'D7'],
      ['D7', null, null],
      ['CM7', null, 'D7'],
      ['D7', null, null],
      ['GM7', 'Em7', null],
      ['Em7', null, 'Em7'],
    ],
  },
  {
    id: 'track-2',
    title: 'Twelve Bar Blues',
    key: 'E',
    mode: 'major',
    timeSignature: '3/4',
    chords: [
      { measureNo: 1, sequenceNo: 1, chordName: 'E7' },
      { measureNo: 2, sequenceNo: 1, chordName: 'A7' },
      { measureNo: 3, sequenceNo: 1, chordName: 'E7' },
      { measureNo: 4, sequenceNo: 1, chordName: 'B7' },
    ],
    genre: 'Blues',
    bpm: 95,
    difficulty: 'intermediate',
    duration: '2:10',
    popularity: 74,
    createdAt: '2026-06-18',
    creator: 'ADMIN',
    chordProgression: [
      ['E7', 'A7', null],
      ['A7', null, 'A7'],
      ['E7', null, 'B7'],
      ['B7', null, null],
      ['E7', null, 'B7'],
      ['B7', null, null],
      ['E7', 'A7', null],
      ['A7', null, 'A7'],
    ],
  },
];
