import type { Track } from '@/types/track';

export const GENRES = ['장르 전체', 'Jazz', 'Pop', 'Blues', '기타'] as const;

export const RECOMMENDED_TRACKS: Track[] = [
  {
    id: 'recommended-1',
    title: 'Jazz Standard Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: ['Cmaj7', 'Am7', 'Dm7', 'G7'],
    genre: 'Jazz',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:30',
    popularity: 92,
    createdAt: '2026-07-01',
  },
  {
    id: 'recommended-2',
    title: 'Pop Ballad Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: ['G', 'Em', 'C', 'D'],
    genre: 'Pop',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:50',
    popularity: 88,
    createdAt: '2026-07-02',
  },
  {
    id: 'recommended-3',
    title: 'Blues in C',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: ['C7', 'F7', 'C7', 'G7'],
    genre: 'Blues',
    bpm: 90,
    difficulty: 'intermediate',
    duration: '2:30',
    popularity: 81,
    createdAt: '2026-06-28',
  },
  {
    id: 'recommended-4',
    title: 'Rock Riff Practice',
    key: 'E',
    mode: 'minor',
    timeSignature: '4/4',
    chords: ['Em', 'C', 'G', 'D'],
    genre: '기타',
    bpm: 140,
    difficulty: 'intermediate',
    duration: '1:20',
    popularity: 76,
    createdAt: '2026-07-03',
  },
];

export const ALL_TRACKS: Track[] = [
  {
    id: 'track-1',
    title: 'Jazz Standard Practice',
    key: 'C',
    mode: 'major',
    timeSignature: '4/4',
    chords: ['Cmaj7', 'Am7', 'Dm7', 'G7'],
    genre: 'Jazz',
    bpm: 120,
    difficulty: 'beginner',
    duration: '0:30',
    popularity: 92,
    createdAt: '2026-07-01',
  },
  {
    id: 'track-2',
    title: 'Twelve Bar Blues',
    key: 'E',
    mode: 'major',
    timeSignature: '4/4',
    chords: ['E7', 'A7', 'E7', 'B7'],
    genre: 'Blues',
    bpm: 95,
    difficulty: 'intermediate',
    duration: '2:10',
    popularity: 74,
    createdAt: '2026-06-18',
  },
];
